name: Heartless
version: '${project.version}'
main: uk.sleepylux.heartlessplugin.HeartlessPlugin
api-version: '1.20'
commands:
  credits:
    description: Get the plugin credits
    usage: /credits
  revive:
    description: Revive a user
    usage: /revive
  getHeart:
    description: Get a players heart
    usage: /getHeart <Playername>